
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-23T09:27:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c224a80372d17ab1e803c9dfc6a2ffc282d0dc49",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
