
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-14T10:40:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d251db03b159447331ac9ae63e13d295d75bad70",
 "version": "0.13.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
